[package]
name = "got-board-api-v3"
version = "0.1.0"
authors = ["Rafael Borgonovi Tauil <rafael@tauil.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
